name: Label New Issues

on:
  issues:
    types:
      - reopened
      - opened

jobs:
  add-label:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Check if issue has a milestone
        id: check_milestone
        uses: actions/github-script@v6
        with:
          script: |
            const issue = context.payload.issue;
            if (!issue.milestone) {
              return { hasMilestone: false };
            }
            return { hasMilestone: true };

      - name: Add "needs milestone" label
        if: steps.check_milestone.outputs.hasMilestone == 'false'
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: 'needs milestone'
